name: CI

on:
  push:
    branches: [main]
    tags: ["v*"]
  pull_request:
    branches: ["*"]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18, 22]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: "yarn"

      - name: Install dependencies
        run: corepack enable && yarn install --immutable

      - name: Lint
        run: yarn lint:ci

      - name: Build
        run: yarn build

      - name: Test
        run: yarn test

      - name: Publish to NPM
        if: ${{ startsWith(github.ref, 'refs/tags/v') && matrix.node-version == 22 }}
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_PUBLISH_TOKEN }}
